apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}
  dnsNames:
    - {{ .Values.ingress.host }}
  duration: 2160h        # 90 days
  renewBefore: 360h      # 15 days before expiry
  issuerRef:
    name: {{ .Values.certManager.issuerName }}
    kind: ClusterIssuer
